#!/usr/bin/env python3
"""从 webfonts/ 生成精简发布包（只保留常用字重）。

用法:
  python make-slim.py
  python make-slim.py --preset core
  python make-slim.py --weights 400,500,700 --no-italic
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

WEIGHT_TO_FILE = {
    100: "Thin",
    200: "ExtraLight",
    300: "Light",
    400: "Regular",
    500: "Medium",
    600: "SemiBold",
    700: "Bold",
    800: "ExtraBold",
    900: "Black",
}

PRESETS = {
    "core": [400, 700],
    "standard": [400, 500, 600, 700],
    "light": [400, 500, 700],
}


def main() -> None:
    p = argparse.ArgumentParser(description="生成精简 WOFF2 发布包")
    p.add_argument("--preset", choices=PRESETS.keys(), default="standard")
    p.add_argument("--weights", help="逗号分隔 font-weight，如 400,500,700")
    p.add_argument("--no-italic", action="store_true")
    p.add_argument(
        "--italic-weights",
        default="400,700",
        help="哪些字重附带斜体，默认 400,700；填 all 表示全部",
    )
    p.add_argument("--source", default="webfonts")
    p.add_argument("--out", help="输出目录，默认 packages/slim-<preset>")
    p.add_argument("--family", default="Maple Mono NF CN")
    p.add_argument("--slug", default="maple-mono-nf-cn")
    p.add_argument("--package-name", default="maple-mono-nf-cn-woff2-slim")
    p.add_argument("--version", default="7.9.0")
    args = p.parse_args()

    if args.weights:
        weights = sorted({int(x) for x in args.weights.split(",") if x.strip()})
    else:
        weights = PRESETS[args.preset]
    include_italic = not args.no_italic
    if args.preset == "light" and not args.weights:
        include_italic = False
    if args.italic_weights.strip().lower() == "all":
        italic_weights = set(weights)
    else:
        italic_weights = {int(x) for x in args.italic_weights.split(",") if x.strip()}

    out_dir = Path(args.out or f"packages/slim-{args.preset}")
    src_root = Path(args.source).resolve()
    out_fonts = out_dir / "webfonts"
    out_css = out_dir / "css"
    out_fonts.mkdir(parents=True, exist_ok=True)
    out_css.mkdir(parents=True, exist_ok=True)

    want = []
    for w in weights:
        name = WEIGHT_TO_FILE[w]
        want.append({"weight": w, "style": "normal", "file": f"MapleMono-NF-CN-{name}.woff2"})
        if include_italic and w in italic_weights:
            italic = (
                "MapleMono-NF-CN-Italic.woff2"
                if w == 400
                else f"MapleMono-NF-CN-{name}Italic.woff2"
            )
            want.append({"weight": w, "style": "italic", "file": italic})

    copied = []
    for item in want:
        src = src_root / item["file"]
        if not src.exists():
            print(f"跳过缺失: {item['file']}")
            continue
        shutil.copy2(src, out_fonts / item["file"])
        copied.append(item)

    if not copied:
        raise SystemExit("没有复制到任何字体，请先运行 convert-fonts")

    rules = []
    for c in copied:
        rules.append(
            f"""@font-face {{
  font-family: '{args.family}';
  src: url('../webfonts/{c["file"]}') format('woff2');
  font-weight: {c["weight"]};
  font-style: {c["style"]};
  font-display: swap;
}}"""
        )
    used_weights = sorted({c["weight"] for c in copied})
    header = f"""/* {args.family} — SLIM WOFF2 pack ({args.preset})
 * Weights: {', '.join(map(str, used_weights))}
 * Generated by make-slim.py
 */
"""
    (out_css / f"{args.slug}.css").write_text(header + "\n\n" + "\n\n".join(rules) + "\n", encoding="utf-8")

    cdn_rules = [
        f"""@font-face {{
  font-family: '{args.family}';
  src: url('__CDN_BASE__/webfonts/{c["file"]}') format('woff2');
  font-weight: {c["weight"]};
  font-style: {c["style"]};
  font-display: swap;
}}"""
        for c in copied
    ]
    (out_css / f"{args.slug}.cdn.css").write_text(
        f"/* SLIM — 替换 __CDN_BASE__ */\n\n" + "\n\n".join(cdn_rules) + "\n",
        encoding="utf-8",
    )

    if Path("LICENSE.txt").exists():
        shutil.copy2("LICENSE.txt", out_dir / "LICENSE.txt")

    total_mb = sum((out_fonts / c["file"]).stat().st_size for c in copied) / 1024 / 1024
    files = [f"webfonts/{c['file']}" for c in copied]
    files += [f"css/{args.slug}.css", f"css/{args.slug}.cdn.css", "LICENSE.txt", "README.md"]
    pkg = {
        "name": args.package_name,
        "version": args.version,
        "description": f"{args.family} slim web fonts (WOFF2, {args.preset})",
        "license": "OFL-1.1",
        "files": files,
        "keywords": ["font", "woff2", "webfont", args.slug, "slim"],
    }
    (out_dir / "package.json").write_text(
        json.dumps(pkg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    rows = "\n".join(f"| {c['file']} | {c['weight']} | {c['style']} |" for c in copied)
    (out_dir / "README.md").write_text(
        f"""# {args.package_name}

{args.family} 精简 WOFF2 包（**{args.preset}**，{len(copied)} 个文件，约 {total_mb:.2f} MB）。

## 字重

| 文件 | weight | style |
|------|--------|-------|
{rows}

## 使用

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/{args.package_name}@{args.version}/css/{args.slug}.css" />
```

许可证：SIL OFL 1.1。
""",
        encoding="utf-8",
    )

    print(f"\n精简包: {out_dir}")
    print(f"预设: {args.preset} | 权重: {used_weights} | 文件: {len(copied)} | 合计: {total_mb:.2f} MB")
    print(f"CDN: https://cdn.jsdelivr.net/npm/{args.package_name}@{args.version}")


if __name__ == "__main__":
    main()
