<#
.SYNOPSIS
  从 webfonts/ 生成精简发布包（只保留常用字重）。

.DESCRIPTION
  预设:
    core     4 字重 ~25MB  Regular/Italic/Bold/BoldItalic  — 最稳，优先用于 npm
    standard 6 字重 ~37MB  core + Medium/SemiBold          — 覆盖常见 UI
    light    3 字重 ~18MB  Regular/Medium/Bold             — 极简，无斜体

.EXAMPLE
  .\make-slim.ps1
  .\make-slim.ps1 -Preset core
  .\make-slim.ps1 -Weights 400,500,700 -OutDir packages\slim-custom
  .\make-slim.ps1 -Preset standard -PackageName maple-mono-nf-cn-slim -Version 7.9.0
#>
[CmdletBinding()]
param(
  [ValidateSet("core", "standard", "light")]
  [string]$Preset = "standard",

  # 显式指定 font-weight 列表（覆盖 Preset）；会带上对应 Italic（若存在）
  [int[]]$Weights,

  [switch]$IncludeItalic = $true,
  # 哪些字重附带斜体；默认 400,700；传 'all' 表示全部
  [string]$ItalicWeights = "400,700",
  [string]$SourceDir = "webfonts",
  [string]$OutDir,
  [string]$FamilyName = "Maple Mono NF CN",
  [string]$Slug = "maple-mono-nf-cn",
  [string]$PackageName = "maple-mono-nf-cn-woff2-slim",
  [string]$Version = "7.9.0"
)

$ErrorActionPreference = "Stop"

if (-not $Weights) {
  switch ($Preset) {
    "core"     { $Weights = @(400, 700) }
    "standard" { $Weights = @(400, 500, 600, 700) }
    "light"    { $Weights = @(400, 500, 700) }
  }
  if ($Preset -eq "light") { $IncludeItalic = $false }
}

$italicSet = if ($ItalicWeights.Trim().ToLowerInvariant() -eq "all") {
  [System.Collections.Generic.HashSet[int]]::new([int[]]$Weights)
} else {
  $s = [System.Collections.Generic.HashSet[int]]::new()
  foreach ($x in ($ItalicWeights -split ',')) {
    if ($x.Trim()) { [void]$s.Add([int]$x.Trim()) }
  }
  $s
}

if (-not $OutDir) { $OutDir = Join-Path "packages" "slim-$Preset" }

# weight → 文件后缀（与 convert 脚本一致）
$WeightToFile = @{
  100 = "Thin"
  200 = "ExtraLight"
  300 = "Light"
  400 = "Regular"
  500 = "Medium"
  600 = "SemiBold"
  700 = "Bold"
  800 = "ExtraBold"
  900 = "Black"
}

$want = @()
foreach ($w in ($Weights | Sort-Object -Unique)) {
  $name = $WeightToFile[$w]
  if (-not $name) { throw "不支持的 weight: $w" }
  $want += [pscustomobject]@{ Weight = $w; Style = "normal"; File = "MapleMono-NF-CN-$name.woff2" }
  if ($IncludeItalic -and $italicSet.Contains($w)) {
    $italicFile = if ($w -eq 400) { "MapleMono-NF-CN-Italic.woff2" } else { "MapleMono-NF-CN-${name}Italic.woff2" }
    $want += [pscustomobject]@{ Weight = $w; Style = "italic"; File = $italicFile }
  }
}

$srcRoot = (Resolve-Path $SourceDir).Path
$outFonts = Join-Path $OutDir "webfonts"
$outCss = Join-Path $OutDir "css"
New-Item -ItemType Directory -Force -Path $outFonts, $outCss | Out-Null

$copied = @()
$missing = @()
foreach ($item in $want) {
  $src = Join-Path $srcRoot $item.File
  if (-not (Test-Path $src)) {
    $missing += $item.File
    continue
  }
  Copy-Item $src (Join-Path $outFonts $item.File) -Force
  $copied += $item
}

if (-not $copied) { throw "没有复制到任何字体，请先运行 convert-fonts" }
if ($missing) {
  Write-Warning "跳过缺失文件: $($missing -join ', ')"
}

$rules = foreach ($c in $copied) {
  @"
@font-face {
  font-family: '$FamilyName';
  src: url('../webfonts/$($c.File)') format('woff2');
  font-weight: $($c.Weight);
  font-style: $($c.Style);
  font-display: swap;
}
"@
}

$cssPath = Join-Path $outCss "$Slug.css"
$css = @"
/* $FamilyName — SLIM WOFF2 pack ($Preset)
 * Weights: $(($copied | ForEach-Object { $_.Weight } | Sort-Object -Unique) -join ', ')
 * Generated by make-slim.ps1
 */

$($rules -join "`n`n")
"@
Set-Content -Path $cssPath -Value $css -Encoding utf8

# CDN 模板
$cdnRules = foreach ($c in $copied) {
  @"
@font-face {
  font-family: '$FamilyName';
  src: url('__CDN_BASE__/webfonts/$($c.File)') format('woff2');
  font-weight: $($c.Weight);
  font-style: $($c.Style);
  font-display: swap;
}
"@
}
Set-Content -Path (Join-Path $outCss "$Slug.cdn.css") -Value (@"
/* $FamilyName SLIM — 替换 __CDN_BASE__ 后用于 jsDelivr */
$($cdnRules -join "`n`n")
"@) -Encoding utf8

# LICENSE / README
if (Test-Path "LICENSE.txt") { Copy-Item "LICENSE.txt" (Join-Path $OutDir "LICENSE.txt") -Force }

$files = @($copied | ForEach-Object { "webfonts/$($_.File)" })
$files += @("css/$Slug.css", "css/$Slug.cdn.css", "LICENSE.txt", "README.md")

$totalMB = [math]::Round((($copied | ForEach-Object { (Get-Item (Join-Path $outFonts $_.File)).Length } | Measure-Object -Sum).Sum) / 1MB, 2)

$pkg = [ordered]@{
  name        = $PackageName
  version     = $Version
  description = "$FamilyName slim web fonts (WOFF2, $Preset)"
  license     = "OFL-1.1"
  files       = $files
  keywords    = @("font", "woff2", "webfont", $Slug, "slim")
}
$pkg | ConvertTo-Json -Depth 5 | Set-Content (Join-Path $OutDir "package.json") -Encoding utf8

$readme = @"
# $PackageName

$FamilyName 精简 WOFF2 包（**$Preset**，$($copied.Count) 个文件，约 $totalMB MB）。

## 字重

| 文件 | weight | style |
|------|--------|-------|
$($copied | ForEach-Object { "| $($_.File) | $($_.Weight) | $($_.Style) |" } | Out-String)

## 使用

\`\`\`html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/$PackageName@$Version/css/$Slug.css" />
\`\`\`

或本地：

\`\`\`html
<link rel="stylesheet" href="css/$Slug.css" />
\`\`\`

许可证：SIL OFL 1.1，见 LICENSE.txt。
"@
Set-Content -Path (Join-Path $OutDir "README.md") -Value $readme -Encoding utf8

Write-Host "`n精简包已生成: $OutDir" -ForegroundColor Green
Write-Host "预设: $Preset | 字重: $(($copied | ForEach-Object { $_.Weight } | Sort-Object -Unique) -join ', ') | 文件: $($copied.Count) | 合计: $totalMB MB"
Write-Host "npm 包名: $PackageName@$Version"
Write-Host "CDN 前缀: https://cdn.jsdelivr.net/npm/$PackageName@$Version"
$copied | Format-Table Weight, Style, File -AutoSize
